platformOwners:
    - vikrant@vapusdata.com
platformAccount: 
    name: VapusData Sandbox 
    creator: vikrant@vapusdata.com
platformAccountDomain:
    name: VapusData Sandbox Service Domain
datamesh:
    name: VapusData DataMesh
    creator: vikrant@vapusdata.com