platformSvc:
  port: "9013"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "https://demo.vapusdata.com"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9013"
  httpGwPort: "9015"
aistudioSvc:
  port: "9019"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "https://demo.vapusdata.com"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9019"
  httpGwPort: "9020"
aigateway:
  port: "9017"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "https://demo.vapusdata.com"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9017"
webappSvc:
  port: "9014"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "http://127.0.0.1:9014"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9014"
nabhikserver:
  port: "9021"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "https://demo.vapusdata.com"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9021"
  httpGwPort: "9023"
aiutility:
  port: "9028"
  serviceName: "localhost"
  scheme: "http"
  externalUrl: "https://demo.vapusdata.com"
  svcType: "clusterIP"
  addr: "localhost"
  servicePort: "9028"
  httpGwPort: "9023"
externalUrl: "http://127.0.0.1:9014"
gatewayUrl: "http://127.0.0.1:9017"